name: Build Package

on:
  pull_request:
  release:
  push:
    branches:
      - main

jobs:
  builds_package:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mapmatcher
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
  
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        python -m pip install --upgrade pip
        pip install -e .[build]

    - name: Builds package
      run: |
      python -m build -n
      python -m build --wheel

    - name: Stores artifacts along with the workflow result
      uses: actions/upload-artifact@v4
      with:
        name: library
        path: dist/*.*
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  upload_all:
    needs: [builds_package]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1