name: Build Package

on:
  pull_request:
  release:
  push:
    branches:
      - main

jobs:
  builds_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
  
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        python -m pip install --upgrade pip
        pip install -e .[build]

    - name: Builds package
      run: python -m build -n

    - name: Stores artifacts along with the workflow result
      uses: actions/upload-artifact@v4
      with:
        name: library
        path: dist/*.whl
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    - name: Publish wheels to PyPI
      if: ${{ github.event_name == 'release'}}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install twine
        twine upload dist/*.whl
        twine upload dist/*.gz
