name: Build Package

on:
  pull_request:
  release:
  push:
    branches:
      - main

jobs:
  builds_package:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mapmatcher
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
  
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        python -m pip install --upgrade pip
        pip install -e .[build]

    - name: Builds package
      run: python -m build -n

    - name: Stores artifacts along with the workflow result
      uses: actions/upload-artifact@v4
      with:
        name: library
        path: dist/*.whl
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    - name: Publish to PyPI
      # if: ${{ github.event_name == 'release'}}
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}