name: Scheduled Test

on:
  push:
    branches: [develop]
  pull_request:
#  schedule:
#    - cron: '0 8 1 * *'
#  repository_dispatch:
#    types: [ custom-event ]

jobs:
  scheduled_test:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
        os: [ windows-latest, ubuntu-latest ]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

      - name: Install dependencies with develop aequilibrae
        run: |
          python -m pip install -U pip
          pip install git+https://github.com/AequilibraE/aequilibrae.git@develop
          touch ./pyproject.toml
          pip install -e .[testing]

      - name: Download spatialite on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libspatialite-dev
          sudo apt install -y libsqlite3-mod-spatialite
          pip3 install spatialite
          sudo ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite

      - name: Download spatialite on Windows
        if: matrix.os == 'windows-latest'
        run: python tests/setup_windows_spatialite.py

      - name: Runs unit tests
        run: |
          python -m pytest -v