name: Scheduled Test

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  scheduled_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.10'

      - name: Install dependencies with develop aequilibrae
        run: |
          uv sync --extra testing
          uv add "aequilibrae @ git+https://github.com/AequilibraE/aequilibrae.git@develop"
      
      - name: Run tests
        run: |
          uv run pytest --cov-report term --cov-config=.coveragerc --cov=mapmatcher tests