name: Scheduled Test

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  scheduled_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python 3.10
        run: uv python install 3.10

      - name: Install dependencies with develop aequilibrae
        run: |
          uv pip sync --extra testing
          uv add "git+https://github.com/AequilibraE/aequilibrae.git@develop"
          uv pip install -e .[testing]

      - name: Download spatialite on Linux
        run: |
          sudo apt-get update
          python -m pip install -U setuptools
          sudo apt-get install libsqlite3-mod-spatialite
          sudo apt-get install -y libspatialite-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite
      
      - name: Run tests
        run: |
          uv run pytest --cov-report term --cov-config=.coveragerc --cov=mapmatcher tests